@startuml
left to right direction
skin rose

package objects{
    Class Instrumento{
        -codigo: String
        -precio: int
        -stock: int
        -nombre: String
        -material: String

        +Instrumento(codigo: String, precio: int, stock: int, nombre: String, material: String)
        +get's()
        +setStock(stock: int): void
    }

    Class Cuerda{
        -tipoCuerda: String
        -cantidadCuerdas: int
        -tipo: String

        +Cuerda(codigo: String, precio: int, stock: int, nombre: String, material: String, tipoCuerda: String, cantidadCuerdas: int, tipo: String)
        +get's()
    }

    Class Percusion{
        -tipoPercusion: String
        -altura: String

        +Percusion(codigo: String, precio: int, stock: int, nombre: String, material: String, tipoPercusion: String, altura: String)
        +get's()

    }

    Class Viento{
        +Viento(codigo: String, precio: int, stock: int, nombre: String, material: String)
        +get's()
    }
}

Instrumento^--Cuerda
Instrumento^--Percusion
Instrumento^--Viento

package contenedores{
    Class ListaInstrumento{
        -instrumentos: Instrumento[]
        -cantInstrumentos: int
        -maximo: int

        +ListaInstrumento(maximo: int)
        +getCantInstrumentos(): int
        +getMaximo(): int
        +agregar(instrumento: Instrumento): void
        +existe(codigo: String): boolean
        +buscar(codigo: String): Instrumento
    }
}

Instrumento o--* ListaInstrumento

package system{
    interface Sistema <<interface>>{
        +agregarInstrumento(direccionArchivo: String): void
        +venderInstrumentoImpl(codigo: String): void
        +consultarInventario(): String
        +cierre(estado: boolean): boolean
    }

    Class SistemaImpl{
        -totalInstrumentos: ListaInstrumento
        -instrumentosCuerda: ListaInstrumento
        -instrumentosPercusion: ListaInstrumento
        -instrumentosViento: ListaInstrumento

        +SistemaImpl()
        +menu(): void
    }
}

Sistema^..SistemaImpl: implemets
SistemaImpl"1"--"*"Instrumento:  posee >
@enduml